// Code generated by qtc from "base.html". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line templates/layout/base.html:1
package layout

//line templates/layout/base.html:1
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line templates/layout/base.html:1
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line templates/layout/base.html:2
type Base interface {
//line templates/layout/base.html:2
	CSS() string
//line templates/layout/base.html:2
	StreamCSS(qw422016 *qt422016.Writer)
//line templates/layout/base.html:2
	WriteCSS(qq422016 qtio422016.Writer)
//line templates/layout/base.html:2
	JS() string
//line templates/layout/base.html:2
	StreamJS(qw422016 *qt422016.Writer)
//line templates/layout/base.html:2
	WriteJS(qq422016 qtio422016.Writer)
//line templates/layout/base.html:2
	Title() string
//line templates/layout/base.html:2
	StreamTitle(qw422016 *qt422016.Writer)
//line templates/layout/base.html:2
	WriteTitle(qq422016 qtio422016.Writer)
//line templates/layout/base.html:2
	Body() string
//line templates/layout/base.html:2
	StreamBody(qw422016 *qt422016.Writer)
//line templates/layout/base.html:2
	WriteBody(qq422016 qtio422016.Writer)
//line templates/layout/base.html:2
}

//line templates/layout/base.html:10
func StreamBaseLayout(qw422016 *qt422016.Writer, b Base) {
//line templates/layout/base.html:10
	qw422016.N().S(`

<!DOCTYPE html>

<html lang="pt">

    <!-- begin::Head -->
    <head>
        <base href="">
        <meta charset="utf-8" />
        <title>`)
//line templates/layout/base.html:20
	b.StreamTitle(qw422016)
//line templates/layout/base.html:20
	qw422016.N().S(` | E-Commerce</title>
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>

        <style>	
        #title {
        margin: 30px 30px;
        padding: 10px 0;
        text-align: left;
        }

        #main-container {
        margin: 40px 40px;
        padding: 10px 0;
        text-align: center;
        }

        #aolado {
        flex-direction: column;
        }

        .container {
        display: flex;
        justify-content: center;
        }
        .center {
        width: 800px;
        display: flex;
        justify-content: center;
        }
    </style>
    </head>

    <!-- end::Head -->

    <!-- begin::Body -->
    <body>

        `)
//line templates/layout/base.html:63
	b.StreamBody(qw422016)
//line templates/layout/base.html:63
	qw422016.N().S(`

    </body>
        
        `)
//line templates/layout/base.html:67
	b.StreamJS(qw422016)
//line templates/layout/base.html:67
	qw422016.N().S(`

`)
//line templates/layout/base.html:69
}

//line templates/layout/base.html:69
func WriteBaseLayout(qq422016 qtio422016.Writer, b Base) {
//line templates/layout/base.html:69
	qw422016 := qt422016.AcquireWriter(qq422016)
//line templates/layout/base.html:69
	StreamBaseLayout(qw422016, b)
//line templates/layout/base.html:69
	qt422016.ReleaseWriter(qw422016)
//line templates/layout/base.html:69
}

//line templates/layout/base.html:69
func BaseLayout(b Base) string {
//line templates/layout/base.html:69
	qb422016 := qt422016.AcquireByteBuffer()
//line templates/layout/base.html:69
	WriteBaseLayout(qb422016, b)
//line templates/layout/base.html:69
	qs422016 := string(qb422016.B)
//line templates/layout/base.html:69
	qt422016.ReleaseByteBuffer(qb422016)
//line templates/layout/base.html:69
	return qs422016
//line templates/layout/base.html:69
}
