// Code generated by qtc from "index.html". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line templates/index/index.html:1
package index

//line templates/index/index.html:1
import (
	"github.com/valyala/fasthttp"
)

//line templates/index/index.html:4
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line templates/index/index.html:4
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line templates/index/index.html:5
type IndexPage struct {
	CTX *fasthttp.RequestCtx
}

//line templates/index/index.html:10
func (p *IndexPage) StreamCSS(qw422016 *qt422016.Writer) {
//line templates/index/index.html:10
	qw422016.N().S(` `)
//line templates/index/index.html:10
}

//line templates/index/index.html:10
func (p *IndexPage) WriteCSS(qq422016 qtio422016.Writer) {
//line templates/index/index.html:10
	qw422016 := qt422016.AcquireWriter(qq422016)
//line templates/index/index.html:10
	p.StreamCSS(qw422016)
//line templates/index/index.html:10
	qt422016.ReleaseWriter(qw422016)
//line templates/index/index.html:10
}

//line templates/index/index.html:10
func (p *IndexPage) CSS() string {
//line templates/index/index.html:10
	qb422016 := qt422016.AcquireByteBuffer()
//line templates/index/index.html:10
	p.WriteCSS(qb422016)
//line templates/index/index.html:10
	qs422016 := string(qb422016.B)
//line templates/index/index.html:10
	qt422016.ReleaseByteBuffer(qb422016)
//line templates/index/index.html:10
	return qs422016
//line templates/index/index.html:10
}

//line templates/index/index.html:12
func (p *IndexPage) StreamTitle(qw422016 *qt422016.Writer) {
//line templates/index/index.html:12
	qw422016.N().S(` HomePage `)
//line templates/index/index.html:12
}

//line templates/index/index.html:12
func (p *IndexPage) WriteTitle(qq422016 qtio422016.Writer) {
//line templates/index/index.html:12
	qw422016 := qt422016.AcquireWriter(qq422016)
//line templates/index/index.html:12
	p.StreamTitle(qw422016)
//line templates/index/index.html:12
	qt422016.ReleaseWriter(qw422016)
//line templates/index/index.html:12
}

//line templates/index/index.html:12
func (p *IndexPage) Title() string {
//line templates/index/index.html:12
	qb422016 := qt422016.AcquireByteBuffer()
//line templates/index/index.html:12
	p.WriteTitle(qb422016)
//line templates/index/index.html:12
	qs422016 := string(qb422016.B)
//line templates/index/index.html:12
	qt422016.ReleaseByteBuffer(qb422016)
//line templates/index/index.html:12
	return qs422016
//line templates/index/index.html:12
}

//line templates/index/index.html:15
func (p *IndexPage) StreamBody(qw422016 *qt422016.Writer) {
//line templates/index/index.html:15
	qw422016.N().S(`

Felipe Agger

`)
//line templates/index/index.html:19
}

//line templates/index/index.html:19
func (p *IndexPage) WriteBody(qq422016 qtio422016.Writer) {
//line templates/index/index.html:19
	qw422016 := qt422016.AcquireWriter(qq422016)
//line templates/index/index.html:19
	p.StreamBody(qw422016)
//line templates/index/index.html:19
	qt422016.ReleaseWriter(qw422016)
//line templates/index/index.html:19
}

//line templates/index/index.html:19
func (p *IndexPage) Body() string {
//line templates/index/index.html:19
	qb422016 := qt422016.AcquireByteBuffer()
//line templates/index/index.html:19
	p.WriteBody(qb422016)
//line templates/index/index.html:19
	qs422016 := string(qb422016.B)
//line templates/index/index.html:19
	qt422016.ReleaseByteBuffer(qb422016)
//line templates/index/index.html:19
	return qs422016
//line templates/index/index.html:19
}

//line templates/index/index.html:22
func (p *IndexPage) StreamJS(qw422016 *qt422016.Writer) {
//line templates/index/index.html:22
	qw422016.N().S(` `)
//line templates/index/index.html:22
}

//line templates/index/index.html:22
func (p *IndexPage) WriteJS(qq422016 qtio422016.Writer) {
//line templates/index/index.html:22
	qw422016 := qt422016.AcquireWriter(qq422016)
//line templates/index/index.html:22
	p.StreamJS(qw422016)
//line templates/index/index.html:22
	qt422016.ReleaseWriter(qw422016)
//line templates/index/index.html:22
}

//line templates/index/index.html:22
func (p *IndexPage) JS() string {
//line templates/index/index.html:22
	qb422016 := qt422016.AcquireByteBuffer()
//line templates/index/index.html:22
	p.WriteJS(qb422016)
//line templates/index/index.html:22
	qs422016 := string(qb422016.B)
//line templates/index/index.html:22
	qt422016.ReleaseByteBuffer(qb422016)
//line templates/index/index.html:22
	return qs422016
//line templates/index/index.html:22
}
